//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeledocTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeledocTestDBEntities : DbContext
    {
        public TeledocTestDBEntities()
            : base("name=TeledocTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Founder> Founders { get; set; }
        public virtual DbSet<FirmsFounder> FirmsFounders { get; set; }
    }
}
